default:
    just --list

check:
    cargo check --all-features

test:
    cargo nextest run --all-features
    cargo test --doc --all-features

clip:
    cargo clippy --all-features -- -D warnings

fmt:
    cargo fmt

ci: fmt clip test
    cargo bench --no-run --all-features
    cargo check --no-default-features

bench:
    cargo bench --all-features

doc:
    cargo doc --all-features --no-deps --open

deps-doc:
    cargo doc --document-private-items --no-deps --open

lib-doc:
    cargo doc --all-features --open
